<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ine1Ld0Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Ine1Ld0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ine1Ld0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Sylius\\Component\\Resource\\Symfony\\Request\\State\\Responder' => ['privates', 'Sylius\\Component\\Resource\\Symfony\\Request\\State\\Responder', 'getResponderService', true],
            'sylius.state_responder.api' => ['privates', 'sylius.state_responder.api', 'getSylius_StateResponder_ApiService', true],
            'sylius.state_responder.html' => ['privates', 'sylius.state_responder.html', 'getSylius_StateResponder_HtmlService', true],
        ], [
            'Sylius\\Component\\Resource\\Symfony\\Request\\State\\Responder' => 'Sylius\\Component\\Resource\\Symfony\\Request\\State\\Responder',
            'sylius.state_responder.api' => 'Sylius\\Component\\Resource\\Symfony\\Request\\State\\ApiResponder',
            'sylius.state_responder.html' => 'Sylius\\Component\\Resource\\Symfony\\Request\\State\\TwigResponder',
        ]);
    }
}
