<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QXBcHviService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.QXBcHvi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QXBcHvi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'messenger.transport.sync' => ['privates', 'messenger.transport.sync', 'getMessenger_Transport_SyncService', true],
            'sync' => ['privates', 'messenger.transport.sync', 'getMessenger_Transport_SyncService', true],
        ], [
            'messenger.transport.sync' => '?',
            'sync' => '?',
        ]);
    }
}
