<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_Form_Type_ScienceBookService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'app.form.type.science_book' shared autowired service.
     *
     * @return \App\Form\Type\ScienceBookType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/ScienceBookType.php';

        return $container->privates['app.form.type.science_book'] = new \App\Form\Type\ScienceBookType('App\\Entity\\ScienceBook', ['sylius']);
    }
}
