<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_Factory_SubscriptionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'app.factory.subscription' shared autowired service.
     *
     * @return \App\Subscription\Factory\SubscriptionFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Factory/FactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Subscription/Factory/SubscriptionFactory.php';

        return $container->services['app.factory.subscription'] = new \App\Subscription\Factory\SubscriptionFactory();
    }
}
