<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoardGameCollectionProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\BoardGameBlog\Infrastructure\Sylius\State\Http\Provider\BoardGameCollectionProvider' shared autowired service.
     *
     * @return \App\BoardGameBlog\Infrastructure\Sylius\State\Http\Provider\BoardGameCollectionProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/BoardGameBlog/Infrastructure/Sylius/State/Http/Provider/BoardGameCollectionProvider.php';

        $a = ($container->privates['Sylius\\Component\\Resource\\Grid\\State\\RequestGridProvider'] ?? $container->load('getRequestGridProviderService'));

        if (isset($container->privates['App\\BoardGameBlog\\Infrastructure\\Sylius\\State\\Http\\Provider\\BoardGameCollectionProvider'])) {
            return $container->privates['App\\BoardGameBlog\\Infrastructure\\Sylius\\State\\Http\\Provider\\BoardGameCollectionProvider'];
        }

        return $container->privates['App\\BoardGameBlog\\Infrastructure\\Sylius\\State\\Http\\Provider\\BoardGameCollectionProvider'] = new \App\BoardGameBlog\Infrastructure\Sylius\State\Http\Provider\BoardGameCollectionProvider($a);
    }
}
