<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoardGameTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\BoardGameBlog\Infrastructure\Symfony\Form\Type\BoardGameType' shared autowired service.
     *
     * @return \App\BoardGameBlog\Infrastructure\Symfony\Form\Type\BoardGameType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/BoardGameBlog/Infrastructure/Symfony/Form/Type/BoardGameType.php';

        return $container->privates['App\\BoardGameBlog\\Infrastructure\\Symfony\\Form\\Type\\BoardGameType'] = new \App\BoardGameBlog\Infrastructure\Symfony\Form\Type\BoardGameType();
    }
}
