<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteBoardGameCommandHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\BoardGameBlog\Application\Command\DeleteBoardGameCommandHandler' shared autowired service.
     *
     * @return \App\BoardGameBlog\Application\Command\DeleteBoardGameCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Shared/Application/Command/CommandHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/BoardGameBlog/Application/Command/DeleteBoardGameCommandHandler.php';

        return $container->privates['App\\BoardGameBlog\\Application\\Command\\DeleteBoardGameCommandHandler'] = new \App\BoardGameBlog\Application\Command\DeleteBoardGameCommandHandler(($container->privates['App\\BoardGameBlog\\Infrastructure\\Doctrine\\DoctrineBoardGameRepository'] ?? $container->load('getDoctrineBoardGameRepositoryService')));
    }
}
