<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_TypeExtension_Form_ValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'form.type_extension.form.validator' shared service.
     *
     * @return \Symfony\Component\Form\Extension\Validator\Type\FormTypeValidatorExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/Extension/Validator/Type/BaseValidatorExtension.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/Extension/Validator/Type/FormTypeValidatorExtension.php';

        $a = ($container->privates['validator'] ?? self::getValidatorService($container));

        if (isset($container->privates['form.type_extension.form.validator'])) {
            return $container->privates['form.type_extension.form.validator'];
        }
        $b = ($container->privates['twig.form.renderer'] ?? $container->load('getTwig_Form_RendererService'));

        if (isset($container->privates['form.type_extension.form.validator'])) {
            return $container->privates['form.type_extension.form.validator'];
        }

        return $container->privates['form.type_extension.form.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\FormTypeValidatorExtension($a, false, $b, ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
