<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGridViewFactoryInterfaceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Component\Resource\Grid\View\Factory\GridViewFactoryInterface' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Grid\View\LegacyGridViewFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Grid/View/Factory/GridViewFactoryInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Grid/View/LegacyGridViewFactory.php';

        $a = ($container->services['sylius.grid.resource_view_factory'] ?? $container->load('getSylius_Grid_ResourceViewFactoryService'));

        if (isset($container->services['Sylius\\Component\\Resource\\Grid\\View\\Factory\\GridViewFactoryInterface'])) {
            return $container->services['Sylius\\Component\\Resource\\Grid\\View\\Factory\\GridViewFactoryInterface'];
        }
        $b = ($container->privates['sylius.grid.view_factory.legacy.inner'] ?? $container->load('getSylius_Grid_ViewFactory_Legacy_InnerService'));

        if (isset($container->services['Sylius\\Component\\Resource\\Grid\\View\\Factory\\GridViewFactoryInterface'])) {
            return $container->services['Sylius\\Component\\Resource\\Grid\\View\\Factory\\GridViewFactoryInterface'];
        }

        return $container->services['Sylius\\Component\\Resource\\Grid\\View\\Factory\\GridViewFactoryInterface'] = new \Sylius\Bundle\ResourceBundle\Grid\View\LegacyGridViewFactory($a, $b);
    }
}
