<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHateoas_Serializer_Exclusion_ExpressionLanguageStrategyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'hateoas.serializer.exclusion.expression_language_strategy' shared service.
     *
     * @return \JMS\Serializer\Exclusion\ExpressionLanguageExclusionStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/jms/serializer/src/Exclusion/ExpressionLanguageExclusionStrategy.php';

        return $container->privates['hateoas.serializer.exclusion.expression_language_strategy'] = new \JMS\Serializer\Exclusion\ExpressionLanguageExclusionStrategy(($container->privates['jms_serializer.expression_evaluator'] ?? $container->load('getJmsSerializer_ExpressionEvaluatorService')));
    }
}
