<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHateoas_InlineDeferrer_EmbedsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'hateoas.inline_deferrer.embeds' shared service.
     *
     * @return \Hateoas\Serializer\Metadata\InlineDeferrer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/willdurand/hateoas/src/Serializer/Metadata/InlineDeferrer.php';

        return $container->privates['hateoas.inline_deferrer.embeds'] = new \Hateoas\Serializer\Metadata\InlineDeferrer();
    }
}
