<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHateoas_Configuration_Metadata_ExtensionDriverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'hateoas.configuration.metadata.extension_driver' shared service.
     *
     * @return \Hateoas\Configuration\Metadata\Driver\ExtensionDriver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/jms/metadata/src/Driver/DriverInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/willdurand/hateoas/src/Configuration/Metadata/Driver/ExtensionDriver.php';

        return $container->privates['hateoas.configuration.metadata.extension_driver'] = new \Hateoas\Configuration\Metadata\Driver\ExtensionDriver(($container->privates['hateoas.configuration.metadata.annotation_driver'] ?? $container->load('getHateoas_Configuration_Metadata_AnnotationDriverService')));
    }
}
