<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHateoas_Configuration_Metadata_LazyLoadingDriverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'hateoas.configuration.metadata.lazy_loading_driver' shared service.
     *
     * @return \Metadata\Driver\LazyLoadingDriver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/jms/metadata/src/Driver/DriverInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/jms/metadata/src/Driver/LazyLoadingDriver.php';

        return $container->privates['hateoas.configuration.metadata.lazy_loading_driver'] = new \Metadata\Driver\LazyLoadingDriver($container, 'hateoas.configuration.metadata_driver');
    }
}
