<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHateoas_Configuration_Metadata_XmlDriverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'hateoas.configuration.metadata.xml_driver' shared service.
     *
     * @return \Hateoas\Configuration\Metadata\Driver\XmlDriver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/jms/metadata/src/Driver/DriverInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/jms/metadata/src/Driver/AdvancedDriverInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/jms/metadata/src/Driver/AbstractFileDriver.php';
        include_once \dirname(__DIR__, 6).'/vendor/willdurand/hateoas/src/Configuration/Metadata/Driver/CheckExpressionTrait.php';
        include_once \dirname(__DIR__, 6).'/vendor/willdurand/hateoas/src/Configuration/Metadata/Driver/XmlDriver.php';
        include_once \dirname(__DIR__, 6).'/vendor/jms/serializer/src/Type/ParserInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/jms/serializer/src/Type/Parser.php';

        return $container->privates['hateoas.configuration.metadata.xml_driver'] = new \Hateoas\Configuration\Metadata\Driver\XmlDriver(($container->privates['jms_serializer.metadata.traceable_file_locator'] ?? $container->load('getJmsSerializer_Metadata_TraceableFileLocatorService')), ($container->privates['jms_serializer.expression_evaluator'] ?? $container->load('getJmsSerializer_ExpressionEvaluatorService')), ($container->services['hateoas.configuration.provider'] ?? $container->load('getHateoas_Configuration_ProviderService')), ($container->privates['jms_serializer.type_parser'] ??= new \JMS\Serializer\Type\Parser()));
    }
}
