<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_ExpressionLanguageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.expression_language' shared service.
     *
     * @return \Symfony\Component\ExpressionLanguage\ExpressionLanguage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/jms/serializer-bundle/ExpressionLanguage/BasicSerializerFunctionsProvider.php';
        include_once \dirname(__DIR__, 6).'/vendor/willdurand/hateoas-bundle/Expression/LinkExpressionFunction.php';

        $container->privates['jms_serializer.expression_language'] = $instance = new \Symfony\Component\ExpressionLanguage\ExpressionLanguage();

        $instance->registerProvider(($container->privates['jms_serializer.expression_language.function_provider'] ??= new \JMS\SerializerBundle\ExpressionLanguage\BasicSerializerFunctionsProvider()));
        $instance->registerProvider(($container->privates['hateoas.expression.link_expression_function'] ??= new \Bazinga\Bundle\HateoasBundle\Expression\LinkExpressionFunction()));

        return $instance;
    }
}
