<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_Metadata_ChainDriverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.metadata.chain_driver' shared service.
     *
     * @return \Metadata\Driver\DriverChain
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/jms/metadata/src/Driver/DriverInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/jms/metadata/src/Driver/AdvancedDriverInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/jms/metadata/src/Driver/DriverChain.php';

        return $container->privates['jms_serializer.metadata.chain_driver'] = new \Metadata\Driver\DriverChain([($container->privates['jms_serializer.metadata.yaml_driver'] ?? $container->load('getJmsSerializer_Metadata_YamlDriverService')), ($container->privates['jms_serializer.metadata.xml_driver'] ?? $container->load('getJmsSerializer_Metadata_XmlDriverService')), ($container->privates['jms_serializer.metadata.annotation_driver'] ?? $container->load('getJmsSerializer_Metadata_AnnotationDriverService'))]);
    }
}
