<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_TwigExtension_RuntimeSerializerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.twig_extension.runtime_serializer' shared service.
     *
     * @return \JMS\Serializer\Twig\SerializerRuntimeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 6).'/vendor/jms/serializer/src/Twig/SerializerBaseExtension.php';
        include_once \dirname(__DIR__, 6).'/vendor/jms/serializer/src/Twig/SerializerRuntimeExtension.php';

        return $container->privates['jms_serializer.twig_extension.runtime_serializer'] = new \JMS\Serializer\Twig\SerializerRuntimeExtension('jms_');
    }
}
