<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessengerQueryBusService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Shared\Infrastructure\Symfony\Messenger\MessengerQueryBus' shared autowired service.
     *
     * @return \App\Shared\Infrastructure\Symfony\Messenger\MessengerQueryBus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Shared/Application/Query/QueryBusInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/messenger/HandleTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Symfony/Messenger/MessengerQueryBus.php';

        $a = ($container->privates['query.bus'] ?? $container->load('getQuery_BusService'));

        if (isset($container->privates['App\\Shared\\Infrastructure\\Symfony\\Messenger\\MessengerQueryBus'])) {
            return $container->privates['App\\Shared\\Infrastructure\\Symfony\\Messenger\\MessengerQueryBus'];
        }

        return $container->privates['App\\Shared\\Infrastructure\\Symfony\\Messenger\\MessengerQueryBus'] = new \App\Shared\Infrastructure\Symfony\Messenger\MessengerQueryBus($a);
    }
}
