<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioAlice_FileParser_RegistryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'nelmio_alice.file_parser.registry' shared service.
     *
     * @return \Nelmio\Alice\Parser\ParserRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/nelmio/alice/src/ParserInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/nelmio/alice/src/IsAServiceTrait.php';
        include_once \dirname(__DIR__, 6).'/vendor/nelmio/alice/src/Parser/ParserRegistry.php';
        include_once \dirname(__DIR__, 6).'/vendor/nelmio/alice/src/Parser/ChainableParserInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/nelmio/alice/src/Parser/Chainable/PhpParser.php';
        include_once \dirname(__DIR__, 6).'/vendor/nelmio/alice/src/Parser/Chainable/JsonParser.php';

        return $container->privates['nelmio_alice.file_parser.registry'] = new \Nelmio\Alice\Parser\ParserRegistry([($container->privates['nelmio_alice.file_parser.chainable.yaml'] ?? $container->load('getNelmioAlice_FileParser_Chainable_YamlService')), ($container->privates['nelmio_alice.file_parser.chainable.php'] ??= new \Nelmio\Alice\Parser\Chainable\PhpParser()), ($container->privates['nelmio_alice.file_parser.chainable.json'] ??= new \Nelmio\Alice\Parser\Chainable\JsonParser())]);
    }
}
