<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerfanta_TwigExtensionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'pagerfanta.twig_extension' shared service.
     *
     * @return \Pagerfanta\Twig\Extension\PagerfantaExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 6).'/vendor/pagerfanta/pagerfanta/lib/Twig/Extension/PagerfantaExtension.php';

        return $container->privates['pagerfanta.twig_extension'] = new \Pagerfanta\Twig\Extension\PagerfantaExtension();
    }
}
