<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerfanta_UndefinedCallableHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'pagerfanta.undefined_callable_handler' shared service.
     *
     * @return \BabDev\PagerfantaBundle\Twig\UndefinedCallableHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/babdev/pagerfanta-bundle/src/Twig/UndefinedCallableHandler.php';

        return $container->privates['pagerfanta.undefined_callable_handler'] = new \BabDev\PagerfantaBundle\Twig\UndefinedCallableHandler();
    }
}
