<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuery_Bus_Middleware_HandleMessageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'query.bus.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';

        $a = ($container->privates['query.bus.messenger.handlers_locator'] ?? $container->load('getQuery_Bus_Messenger_HandlersLocatorService'));

        if (isset($container->privates['query.bus.middleware.handle_message'])) {
            return $container->privates['query.bus.middleware.handle_message'];
        }

        $container->privates['query.bus.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware($a, false);

        $instance->setLogger(($container->privates['Psr\\Log\\NullLogger'] ??= new \Psr\Log\NullLogger()));

        return $instance;
    }
}
