<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResourceLoaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ResourceBundle\Routing\ResourceLoader' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Routing\ResourceLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/config/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Routing/ResourceLoader.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Routing/RouteFactoryInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Routing/RouteFactory.php';

        return $container->privates['Sylius\\Bundle\\ResourceBundle\\Routing\\ResourceLoader'] = new \Sylius\Bundle\ResourceBundle\Routing\ResourceLoader(($container->privates['sylius.resource_registry'] ?? self::getSylius_ResourceRegistryService($container)), new \Sylius\Bundle\ResourceBundle\Routing\RouteFactory());
    }
}
