<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestGridProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Sylius\Component\Resource\Grid\State\RequestGridProvider' shared service.
     *
     * @return \Sylius\Component\Resource\Grid\State\RequestGridProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Grid/State/RequestGridProvider.php';

        $a = ($container->services['Sylius\\Component\\Resource\\Grid\\View\\Factory\\GridViewFactoryInterface'] ?? $container->load('getGridViewFactoryInterfaceService'));

        if (isset($container->privates['Sylius\\Component\\Resource\\Grid\\State\\RequestGridProvider'])) {
            return $container->privates['Sylius\\Component\\Resource\\Grid\\State\\RequestGridProvider'];
        }
        $b = ($container->services['sylius.grid.service_grid_provider'] ?? $container->load('getSylius_Grid_ServiceGridProviderService'));

        if (isset($container->privates['Sylius\\Component\\Resource\\Grid\\State\\RequestGridProvider'])) {
            return $container->privates['Sylius\\Component\\Resource\\Grid\\State\\RequestGridProvider'];
        }

        return $container->privates['Sylius\\Component\\Resource\\Grid\\State\\RequestGridProvider'] = new \Sylius\Component\Resource\Grid\State\RequestGridProvider($a, $b);
    }
}
