<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_CustomGridRenderer_Twig_InnerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.custom_grid_renderer.twig.inner' shared service.
     *
     * @return \Sylius\Bundle\GridBundle\Renderer\TwigGridRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Component/Renderer/GridRendererInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Bundle/Renderer/TwigGridRenderer.php';

        $a = ($container->services['twig'] ?? $container->load('getTwigService'));

        if (isset($container->privates['sylius.custom_grid_renderer.twig.inner'])) {
            return $container->privates['sylius.custom_grid_renderer.twig.inner'];
        }
        $b = ($container->services['sylius.registry.grid_field'] ?? $container->load('getSylius_Registry_GridFieldService'));

        if (isset($container->privates['sylius.custom_grid_renderer.twig.inner'])) {
            return $container->privates['sylius.custom_grid_renderer.twig.inner'];
        }
        $c = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->privates['sylius.custom_grid_renderer.twig.inner'])) {
            return $container->privates['sylius.custom_grid_renderer.twig.inner'];
        }

        return $container->privates['sylius.custom_grid_renderer.twig.inner'] = new \Sylius\Bundle\GridBundle\Renderer\TwigGridRenderer($a, $b, $c, ($container->privates['sylius.form_registry.grid_filter'] ?? $container->load('getSylius_FormRegistry_GridFilterService')), '@SyliusGrid/_grid.html.twig', $container->parameters['sylius.grid.templates.action'], []);
    }
}
