<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Templating_Helper_GridService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.templating.helper.grid' shared service.
     *
     * @return \Sylius\Bundle\GridBundle\Templating\Helper\GridHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['sylius.templating.helper.grid'] = $container->createProxy('GridHelperGhostF533c61', static fn () => \GridHelperGhostF533c61::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Bundle/Templating/Helper/GridHelper.php';

        return ($lazyLoad->__construct(($container->services['sylius.custom_grid_renderer.twig'] ?? $container->load('getSylius_CustomGridRenderer_TwigService'))) && false ?: $lazyLoad);
    }
}
