<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_ResourceController_ResourcesResolver_GridAwareService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.resource_controller.resources_resolver.grid_aware' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Grid\Controller\ResourcesResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Bundle/Controller/ResourcesResolverInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Grid/Controller/ResourcesResolver.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Controller/ResourcesResolver.php';

        return $container->services['sylius.resource_controller.resources_resolver.grid_aware'] = new \Sylius\Bundle\ResourceBundle\Grid\Controller\ResourcesResolver(($container->privates['sylius.resource_controller.resources_resolver.grid_aware.inner'] ??= new \Sylius\Bundle\ResourceBundle\Controller\ResourcesResolver()), ($container->services['sylius.grid.chain_provider'] ?? $container->load('getSylius_Grid_ChainProviderService')), ($container->services['sylius.grid.resource_view_factory'] ?? $container->load('getSylius_Grid_ResourceViewFactoryService')));
    }
}
