<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Twig_Context_Factory_DefaultService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.twig.context.factory.default' shared service.
     *
     * @return \Sylius\Component\Resource\Twig\Context\Factory\DefaultContextFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Twig/Context/Factory/ContextFactoryInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Twig/Context/Factory/DefaultContextFactory.php';

        return $container->privates['sylius.twig.context.factory.default'] = new \Sylius\Component\Resource\Twig\Context\Factory\DefaultContextFactory();
    }
}
