<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_ResourceTranslationsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.resource_translations' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Form\Type\ResourceTranslationsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Form/Type/ResourceTranslationsType.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Translation/Provider/TranslationLocaleProviderInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Translation/Provider/ImmutableTranslationLocaleProvider.php';

        return $container->services['sylius.form.type.resource_translations'] = new \Sylius\Bundle\ResourceBundle\Form\Type\ResourceTranslationsType(($container->services['sylius.translation_locale_provider'] ??= new \Sylius\Component\Resource\Translation\Provider\ImmutableTranslationLocaleProvider(['pl_PL', 'en_US', 'de_DE'], 'en_US')));
    }
}
