<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Routing_Factory_OperationRoutePathFactory_Collection_InnerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.routing.factory.operation_route_path_factory.collection.inner' shared service.
     *
     * @return \Sylius\Component\Resource\Symfony\Routing\Factory\OperationRoutePathFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Symfony/Routing/Factory/OperationRoutePathFactoryInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Symfony/Routing/Factory/OperationRoutePathFactory.php';

        return $container->privates['sylius.routing.factory.operation_route_path_factory.collection.inner'] = new \Sylius\Component\Resource\Symfony\Routing\Factory\OperationRoutePathFactory();
    }
}
