<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_GridField_TwigService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.grid_field.twig' shared service.
     *
     * @return \Sylius\Bundle\GridBundle\FieldTypes\TwigFieldType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Component/FieldTypes/FieldTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Bundle/FieldTypes/TwigFieldType.php';

        $a = ($container->services['twig'] ?? $container->load('getTwigService'));

        if (isset($container->services['sylius.grid_field.twig'])) {
            return $container->services['sylius.grid_field.twig'];
        }

        return $container->services['sylius.grid_field.twig'] = new \Sylius\Bundle\GridBundle\FieldTypes\TwigFieldType(($container->services['sylius.grid.data_extractor.property_access'] ?? $container->load('getSylius_Grid_DataExtractor_PropertyAccessService')), $a);
    }
}
