<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Twig_Extension_BulkActionGridService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.twig.extension.bulk_action_grid' shared service.
     *
     * @return \Sylius\Bundle\GridBundle\Twig\BulkActionGridExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Bundle/Twig/BulkActionGridExtension.php';

        $a = ($container->services['sylius.templating.helper.bulk_action_grid'] ?? $container->load('getSylius_Templating_Helper_BulkActionGridService'));

        if (isset($container->privates['sylius.twig.extension.bulk_action_grid'])) {
            return $container->privates['sylius.twig.extension.bulk_action_grid'];
        }

        return $container->privates['sylius.twig.extension.bulk_action_grid'] = new \Sylius\Bundle\GridBundle\Twig\BulkActionGridExtension($a);
    }
}
