<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_ResourceController_ResourcesResolver_GridAware_InnerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.resource_controller.resources_resolver.grid_aware.inner' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Controller\ResourcesResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Bundle/Controller/ResourcesResolverInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Controller/ResourcesResolver.php';

        return $container->privates['sylius.resource_controller.resources_resolver.grid_aware.inner'] = new \Sylius\Bundle\ResourceBundle\Controller\ResourcesResolver();
    }
}
