<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_ExpressionLanguage_Variables_RequestService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.expression_language.variables.request' shared service.
     *
     * @return \Sylius\Component\Resource\Symfony\ExpressionLanguage\RequestVariables
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Symfony/ExpressionLanguage/VariablesInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Symfony/ExpressionLanguage/RequestVariables.php';

        return $container->privates['sylius.expression_language.variables.request'] = new \Sylius\Component\Resource\Symfony\ExpressionLanguage\RequestVariables(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
