<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_DefaultService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.default' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Form\Type\DefaultResourceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Form/Type/DefaultResourceType.php';

        $a = ($container->privates['sylius.registry.form_builder'] ?? $container->load('getSylius_Registry_FormBuilderService'));

        if (isset($container->services['sylius.form.type.default'])) {
            return $container->services['sylius.form.type.default'];
        }

        return $container->services['sylius.form.type.default'] = new \Sylius\Bundle\ResourceBundle\Form\Type\DefaultResourceType(($container->privates['sylius.resource_registry'] ?? self::getSylius_ResourceRegistryService($container)), $a);
    }
}
