<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Translation_TranslatableListener_Doctrine_OrmService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.translation.translatable_listener.doctrine.orm' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\EventListener\ORMTranslatableListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/event-manager/src/EventSubscriber.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/EventListener/ORMTranslatableListener.php';

        return $container->services['sylius.translation.translatable_listener.doctrine.orm'] = new \Sylius\Bundle\ResourceBundle\EventListener\ORMTranslatableListener(($container->privates['sylius.resource_registry'] ?? self::getSylius_ResourceRegistryService($container)), ($container->services['sylius.translatable_entity_locale_assigner'] ?? $container->load('getSylius_TranslatableEntityLocaleAssignerService')));
    }
}
