<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_ValidateService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.listener.validate' shared service.
     *
     * @return \Sylius\Component\Resource\Symfony\EventListener\ValidateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Symfony/EventListener/ValidateListener.php';

        return $container->privates['sylius.listener.validate'] = new \Sylius\Component\Resource\Symfony\EventListener\ValidateListener(($container->privates['sylius.resource_metadata_operation.initiator.http_operation'] ?? self::getSylius_ResourceMetadataOperation_Initiator_HttpOperationService($container)), ($container->privates['validator'] ?? self::getValidatorService($container)));
    }
}
