<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmokeSubscriptionEventsSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Subscription\EventSubscriber\SmokeSubscriptionEventsSubscriber' shared autowired service.
     *
     * @return \App\Subscription\EventSubscriber\SmokeSubscriptionEventsSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Subscription/EventSubscriber/SmokeSubscriptionEventsSubscriber.php';

        return $container->privates['App\\Subscription\\EventSubscriber\\SmokeSubscriptionEventsSubscriber'] = new \App\Subscription\EventSubscriber\SmokeSubscriptionEventsSubscriber();
    }
}
