<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStubMakeGridService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\GridBundle\Command\StubMakeGrid' shared service.
     *
     * @return \Sylius\Bundle\GridBundle\Command\StubMakeGrid
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Bundle/Command/StubCommand.php';
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Bundle/Command/StubMakeGrid.php';

        $container->privates['Sylius\\Bundle\\GridBundle\\Command\\StubMakeGrid'] = $instance = new \Sylius\Bundle\GridBundle\Command\StubMakeGrid();

        $instance->setName('make:grid');

        return $instance;
    }
}
