<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_RespondService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.listener.respond' shared service.
     *
     * @return \Sylius\Component\Resource\Symfony\EventListener\RespondListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Symfony/EventListener/RespondListener.php';

        $a = ($container->privates['sylius.state.responder'] ?? $container->load('getSylius_State_ResponderService'));

        if (isset($container->privates['sylius.listener.respond'])) {
            return $container->privates['sylius.listener.respond'];
        }

        return $container->privates['sylius.listener.respond'] = new \Sylius\Component\Resource\Symfony\EventListener\RespondListener(($container->privates['sylius.resource_metadata_operation.initiator.http_operation'] ?? self::getSylius_ResourceMetadataOperation_Initiator_HttpOperationService($container)), ($container->privates['sylius.context.initiator.legacy_request_context'] ?? self::getSylius_Context_Initiator_LegacyRequestContextService($container)), $a);
    }
}
