<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Routing_RedirectHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.routing.redirect_handler' shared service.
     *
     * @return \Sylius\Component\Resource\Symfony\Routing\RedirectHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Symfony/Routing/RedirectHandlerInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Symfony/Routing/RedirectHandler.php';

        return $container->services['sylius.routing.redirect_handler'] = new \Sylius\Component\Resource\Symfony\Routing\RedirectHandler(($container->services['router'] ?? self::getRouterService($container)), ($container->privates['sylius.expression_language.argument_parser.routing'] ?? $container->load('getSylius_ExpressionLanguage_ArgumentParser_RoutingService')), ($container->services['Sylius\\Component\\Resource\\Symfony\\Routing\\Factory\\OperationRouteNameFactoryInterface'] ??= new \Sylius\Component\Resource\Symfony\Routing\Factory\OperationRouteNameFactory()));
    }
}
