<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_StateMachine_Operation_SymfonyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.state_machine.operation.symfony' shared service.
     *
     * @return \Sylius\Component\Resource\Symfony\Workflow\OperationStateMachine
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/StateMachine/OperationStateMachineInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Symfony/Workflow/OperationStateMachine.php';

        $a = ($container->privates['.workflow.registry'] ?? $container->load('get_Workflow_RegistryService'));

        if (isset($container->privates['sylius.state_machine.operation.symfony'])) {
            return $container->privates['sylius.state_machine.operation.symfony'];
        }

        return $container->privates['sylius.state_machine.operation.symfony'] = new \Sylius\Component\Resource\Symfony\Workflow\OperationStateMachine($a);
    }
}
