<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSMExtensionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'SM\Extension\Twig\SMExtension' shared autowired service.
     *
     * @return \SM\Extension\Twig\SMExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 6).'/vendor/winzou/state-machine/src/SM/Extension/Twig/SMExtension.php';

        $a = ($container->services['SM\\Factory\\FactoryInterface'] ?? $container->load('getFactoryInterfaceService'));

        if (isset($container->privates['SM\\Extension\\Twig\\SMExtension'])) {
            return $container->privates['SM\\Extension\\Twig\\SMExtension'];
        }

        return $container->privates['SM\\Extension\\Twig\\SMExtension'] = new \SM\Extension\Twig\SMExtension($a);
    }
}
