<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStateMachine_PullRequestService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'state_machine.pull_request' shared service.
     *
     * @return \Symfony\Component\Workflow\StateMachine
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/workflow/WorkflowInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/workflow/Workflow.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/workflow/StateMachine.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/workflow/MarkingStore/MarkingStoreInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/workflow/MarkingStore/MethodMarkingStore.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['state_machine.pull_request'])) {
            return $container->privates['state_machine.pull_request'];
        }

        return $container->privates['state_machine.pull_request'] = new \Symfony\Component\Workflow\StateMachine(($container->privates['state_machine.pull_request.definition'] ?? $container->load('getStateMachine_PullRequest_DefinitionService')), new \Symfony\Component\Workflow\MarkingStore\MethodMarkingStore(true, 'currentPlace'), $a, 'pull_request', NULL);
    }
}
