<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_ResourceAutocompleteChoiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.resource_autocomplete_choice' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Form\Type\ResourceAutocompleteChoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Form/Type/ResourceAutocompleteChoiceType.php';

        $a = ($container->privates['sylius.registry.resource_repository'] ?? $container->load('getSylius_Registry_ResourceRepositoryService'));

        if (isset($container->services['sylius.form.type.resource_autocomplete_choice'])) {
            return $container->services['sylius.form.type.resource_autocomplete_choice'];
        }

        return $container->services['sylius.form.type.resource_autocomplete_choice'] = new \Sylius\Bundle\ResourceBundle\Form\Type\ResourceAutocompleteChoiceType($a);
    }
}
