<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_GridOptionsParserService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.grid_options_parser' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Grid\Parser\OptionsParser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Bundle/Grid/Parser/OptionsParserInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Grid/Parser/OptionsParser.php';

        return $container->privates['sylius.grid_options_parser'] = new \Sylius\Bundle\ResourceBundle\Grid\Parser\OptionsParser($container, ($container->privates['sylius.expression_language'] ??= new \Sylius\Bundle\ResourceBundle\ExpressionLanguage\ExpressionLanguage()), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)));
    }
}
