<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_CustomBulkActionGridRenderer_TwigService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.custom_bulk_action_grid_renderer.twig' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Grid\Renderer\TwigBulkActionGridRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Component/Renderer/BulkActionGridRendererInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Grid/Renderer/TwigBulkActionGridRenderer.php';

        $a = ($container->services['twig'] ?? $container->load('getTwigService'));

        if (isset($container->services['sylius.custom_bulk_action_grid_renderer.twig'])) {
            return $container->services['sylius.custom_bulk_action_grid_renderer.twig'];
        }

        return $container->services['sylius.custom_bulk_action_grid_renderer.twig'] = new \Sylius\Bundle\ResourceBundle\Grid\Renderer\TwigBulkActionGridRenderer($a, ($container->privates['sylius.grid_options_parser'] ?? $container->load('getSylius_GridOptionsParserService')), $container->parameters['sylius.grid.templates.bulk_action']);
    }
}
