<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_ResourceController_ResourceDeleteHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.resource_controller.resource_delete_handler' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Controller\ResourceDeleteHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Bundle/Controller/ResourceDeleteHandlerInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Controller/ResourceDeleteHandler.php';

        return $container->privates['sylius.resource_controller.resource_delete_handler'] = new \Sylius\Bundle\ResourceBundle\Controller\ResourceDeleteHandler();
    }
}
