<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_GridFilter_SelectService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.grid_filter.select' shared service.
     *
     * @return \Sylius\Component\Grid\Filter\SelectFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Component/Filtering/FilterInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Component/Filter/SelectFilter.php';

        return $container->services['sylius.grid_filter.select'] = new \Sylius\Component\Grid\Filter\SelectFilter();
    }
}
