<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Subscription\Form\Type\SubscriptionType' shared autowired service.
     *
     * @return \App\Subscription\Form\Type\SubscriptionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Subscription/Form/Type/SubscriptionType.php';

        return $container->privates['App\\Subscription\\Form\\Type\\SubscriptionType'] = new \App\Subscription\Form\Type\SubscriptionType();
    }
}
