<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_State_Processor_EventDispatcherBulkAware_InnerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.state.processor.event_dispatcher_bulk_aware.inner' shared service.
     *
     * @return \Sylius\Component\Resource\State\BulkAwareProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Component/State/BulkAwareProcessor.php';

        $a = ($container->privates['sylius.state.processor.event_dispatcher'] ?? $container->load('getSylius_State_Processor_EventDispatcherService'));

        if (isset($container->privates['sylius.state.processor.event_dispatcher_bulk_aware.inner'])) {
            return $container->privates['sylius.state.processor.event_dispatcher_bulk_aware.inner'];
        }

        return $container->privates['sylius.state.processor.event_dispatcher_bulk_aware.inner'] = new \Sylius\Component\Resource\State\BulkAwareProcessor($a);
    }
}
