<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_State_ResponderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.state.responder' shared service.
     *
     * @return \Sylius\Component\Resource\State\Responder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/State/ResponderInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Component/State/Responder.php';

        $a = ($container->privates['.service_locator.Ine1Ld0'] ?? $container->load('get_ServiceLocator_Ine1Ld0Service'));

        if (isset($container->privates['sylius.state.responder'])) {
            return $container->privates['sylius.state.responder'];
        }

        return $container->privates['sylius.state.responder'] = new \Sylius\Component\Resource\State\Responder($a);
    }
}
