<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_EventSubscriber_OrmMappedSuperClassService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.event_subscriber.orm_mapped_super_class' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\EventListener\ORMMappedSuperClassSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/event-manager/src/EventSubscriber.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/EventListener/AbstractDoctrineSubscriber.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/EventListener/ORMMappedSuperClassSubscriber.php';

        return $container->services['sylius.event_subscriber.orm_mapped_super_class'] = new \Sylius\Bundle\ResourceBundle\EventListener\ORMMappedSuperClassSubscriber(($container->privates['sylius.resource_registry'] ?? self::getSylius_ResourceRegistryService($container)));
    }
}
