<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Repository_ExpressionLanguageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.repository.expression_language' shared service.
     *
     * @return \Symfony\Component\ExpressionLanguage\ExpressionLanguage
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sylius.repository.expression_language'] = new \Symfony\Component\ExpressionLanguage\ExpressionLanguage();
    }
}
