<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_TranslationLocaleProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.translation_locale_provider' shared autowired service.
     *
     * @return \Sylius\Component\Resource\Translation\Provider\ImmutableTranslationLocaleProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Translation/Provider/TranslationLocaleProviderInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Translation/Provider/ImmutableTranslationLocaleProvider.php';

        return $container->services['sylius.translation_locale_provider'] = new \Sylius\Component\Resource\Translation\Provider\ImmutableTranslationLocaleProvider(['pl_PL', 'en_US', 'de_DE'], 'en_US');
    }
}
