<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_Exception_ValidationService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.listener.exception.validation' shared service.
     *
     * @return \Sylius\Component\Resource\Symfony\Validator\EventListener\ValidationExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Symfony/Validator/EventListener/ValidationExceptionListener.php';

        return $container->privates['sylius.listener.exception.validation'] = new \Sylius\Component\Resource\Symfony\Validator\EventListener\ValidationExceptionListener(($container->privates['serializer'] ?? self::getSerializerService($container)));
    }
}
