<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionGridService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Subscription\Grid\SubscriptionGrid' shared autowired service.
     *
     * @return \App\Subscription\Grid\SubscriptionGrid
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Bundle/Grid/GridInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Bundle/Grid/AbstractGrid.php';
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Bundle/Grid/ResourceAwareGridInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Subscription/Grid/SubscriptionGrid.php';

        return $container->privates['App\\Subscription\\Grid\\SubscriptionGrid'] = new \App\Subscription\Grid\SubscriptionGrid();
    }
}
