<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_ResourceController_PagerfantaRepresentationFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.resource_controller.pagerfanta_representation_factory' shared service.
     *
     * @return \Hateoas\Representation\Factory\PagerfantaFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/willdurand/hateoas/src/Representation/Factory/PagerfantaFactory.php';

        return $container->privates['sylius.resource_controller.pagerfanta_representation_factory'] = new \Hateoas\Representation\Factory\PagerfantaFactory();
    }
}
