<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Grid_Field_ValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.grid.field.validator' shared service.
     *
     * @return \Sylius\Component\Grid\Validation\FieldValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Component/Validation/FieldValidatorInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Component/Validation/FieldValidator.php';

        return $container->services['sylius.grid.field.validator'] = new \Sylius\Component\Grid\Validation\FieldValidator();
    }
}
