<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Registry_FormBuilderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.registry.form_builder' shared service.
     *
     * @return \Sylius\Component\Registry\ServiceRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/sylius/registry/src/ServiceRegistryInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/sylius/registry/src/ServiceRegistry.php';

        $container->privates['sylius.registry.form_builder'] = $instance = new \Sylius\Component\Registry\ServiceRegistry('Sylius\\Bundle\\ResourceBundle\\Form\\Builder\\DefaultFormBuilderInterface', 'form builder');

        $instance->register('doctrine/orm', ($container->privates['sylius.form_builder.default'] ?? $container->load('getSylius_FormBuilder_DefaultService')));

        return $instance;
    }
}
