<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_GridField_DatetimeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.grid_field.datetime' shared service.
     *
     * @return \Sylius\Component\Grid\FieldTypes\DatetimeFieldType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Component/FieldTypes/FieldTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/sylius/grid-bundle/src/Component/FieldTypes/DatetimeFieldType.php';

        return $container->services['sylius.grid_field.datetime'] = new \Sylius\Component\Grid\FieldTypes\DatetimeFieldType(($container->services['sylius.grid.data_extractor.property_access'] ?? $container->load('getSylius_Grid_DataExtractor_PropertyAccessService')));
    }
}
