<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShowSubscriptionContextFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Subscription\Twig\Context\Factory\ShowSubscriptionContextFactory' shared autowired service.
     *
     * @return \App\Subscription\Twig\Context\Factory\ShowSubscriptionContextFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Twig/Context/Factory/ContextFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Subscription/Twig/Context/Factory/ShowSubscriptionContextFactory.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Twig/Context/Factory/DefaultContextFactory.php';

        return $container->privates['App\\Subscription\\Twig\\Context\\Factory\\ShowSubscriptionContextFactory'] = new \App\Subscription\Twig\Context\Factory\ShowSubscriptionContextFactory(($container->privates['sylius.twig.context.factory.default'] ??= new \Sylius\Component\Resource\Twig\Context\Factory\DefaultContextFactory()));
    }
}
