<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_TranslatableEntityLocaleAssignerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.translatable_entity_locale_assigner' shared service.
     *
     * @return \Sylius\Component\Resource\Translation\TranslatableEntityLocaleAssigner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Translation/TranslatableEntityLocaleAssignerInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Translation/TranslatableEntityLocaleAssigner.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Translation/Provider/TranslationLocaleProviderInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Component/Translation/Provider/ImmutableTranslationLocaleProvider.php';

        return $container->services['sylius.translatable_entity_locale_assigner'] = new \Sylius\Component\Resource\Translation\TranslatableEntityLocaleAssigner(($container->services['sylius.translation_locale_provider'] ??= new \Sylius\Component\Resource\Translation\Provider\ImmutableTranslationLocaleProvider(['pl_PL', 'en_US', 'de_DE'], 'en_US')));
    }
}
