<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Storage_SessionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.storage.session' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Storage\SessionStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Bundle/Storage/SessionStorage.php';

        return $container->services['sylius.storage.session'] = new \Sylius\Bundle\ResourceBundle\Storage\SessionStorage(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
