<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_TypeExtension_Form_RequestHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.form.type_extension.form.request_handler' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Form\Extension\HttpFoundation\HttpFoundationRequestHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/RequestHandlerInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php';

        return $container->privates['sylius.form.type_extension.form.request_handler'] = new \Sylius\Bundle\ResourceBundle\Form\Extension\HttpFoundation\HttpFoundationRequestHandler();
    }
}
