<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_ResourceController_ResourceUpdateHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.resource_controller.resource_update_handler' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Controller\ResourceUpdateHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Bundle/Controller/ResourceUpdateHandlerInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Bundle/Controller/ResourceUpdateHandler.php';

        return $container->privates['sylius.resource_controller.resource_update_handler'] = new \Sylius\Bundle\ResourceBundle\Controller\ResourceUpdateHandler(NULL);
    }
}
