<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_FormService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.listener.form' shared service.
     *
     * @return \Sylius\Component\Resource\Symfony\EventListener\FormListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Component/Symfony/EventListener/FormListener.php';

        $a = ($container->services['Symfony\\Component\\Form\\FormFactoryInterface'] ?? $container->load('getFormFactoryInterfaceService'));

        if (isset($container->privates['sylius.listener.form'])) {
            return $container->privates['sylius.listener.form'];
        }

        return $container->privates['sylius.listener.form'] = new \Sylius\Component\Resource\Symfony\EventListener\FormListener(($container->privates['sylius.resource_metadata_operation.initiator.http_operation'] ?? self::getSylius_ResourceMetadataOperation_Initiator_HttpOperationService($container)), ($container->privates['sylius.context.initiator.legacy_request_context'] ?? self::getSylius_Context_Initiator_LegacyRequestContextService($container)), $a);
    }
}
