<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflow_BlogPublishingService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'workflow.blog_publishing' shared service.
     *
     * @return \Symfony\Component\Workflow\Workflow
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/workflow/WorkflowInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/workflow/Workflow.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/workflow/MarkingStore/MarkingStoreInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/workflow/MarkingStore/MethodMarkingStore.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['workflow.blog_publishing'])) {
            return $container->privates['workflow.blog_publishing'];
        }

        return $container->privates['workflow.blog_publishing'] = new \Symfony\Component\Workflow\Workflow(($container->privates['workflow.blog_publishing.definition'] ?? $container->load('getWorkflow_BlogPublishing_DefinitionService')), new \Symfony\Component\Workflow\MarkingStore\MethodMarkingStore(false, 'currentPlace'), $a, 'blog_publishing', NULL);
    }
}
