<?php

namespace ContainerBoRyxcn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflow_TwigExtensionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'workflow.twig_extension' shared service.
     *
     * @return \Symfony\Bridge\Twig\Extension\WorkflowExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/twig-bridge/Extension/WorkflowExtension.php';

        $a = ($container->privates['.workflow.registry'] ?? $container->load('get_Workflow_RegistryService'));

        if (isset($container->privates['workflow.twig_extension'])) {
            return $container->privates['workflow.twig_extension'];
        }

        return $container->privates['workflow.twig_extension'] = new \Symfony\Bridge\Twig\Extension\WorkflowExtension($a);
    }
}
