<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBoRyxcn\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBoRyxcn/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerBoRyxcn.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerBoRyxcn\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerBoRyxcn\App_KernelTestDebugContainer([
    'container.build_hash' => 'BoRyxcn',
    'container.build_id' => '5043b21a',
    'container.build_time' => 1687274174,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBoRyxcn');
