name: Build

on:
    push:
        branches-ignore:
            - 'dependabot/**'
            - 'upmerge/**'
    pull_request: ~
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday
    workflow_dispatch: ~

jobs:
    tests:
        runs-on: ubuntu-latest
        name: >
            PHP ${{ matrix.php }},
            Symfony ${{ matrix.symfony }},
            ORM ${{ matrix.orm }}
            ${{ matrix['behat-transliterator'] != '' && matrix['gedmo-doctrine-extensions'] != ''
                && format('(with Behat transliterator {0} & Gedmo {1})', matrix['behat-transliterator'], matrix['gedmo-doctrine-extensions'])
                || '' }}
            ${{ matrix['fos-rest-bundle'] != ''
                && format('(with FriendsOfSymfony Rest Bundle {0})', matrix['fos-rest-bundle'])
                || '' }}
        strategy:
            fail-fast: false
            matrix:
                orm: ['2.*', '3.*']
                php: ["8.2", "8.3"]
                behat-transliterator: [""]
                composer-flags: ['--no-scripts --prefer-stable --prefer-dist']
                gedmo-doctrine-extensions: [""]
                fos-rest-bundle: [""]
                symfony: ["6.4.*", "7.4.*"]
                include:
                    # with Behat transliterator and Gedmo Doctrine extensions optional packages
                    -   behat-transliterator: '^1.2'
                        gedmo-doctrine-extensions: '^3.17.1'
                        fos-rest-bundle: '^3.7'
                        php: "8.3"
                        orm: "3.*"
                        symfony: "7.4.*"
                    # with FriendsOfSymfony Rest Bundle optional package
                    -   fos-rest-bundle: '^3.7'
                        php: "8.3"
                        orm: "3.*"
                        symfony: "7.4.*"

        steps:
            -
                uses: actions/checkout@v4

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    extensions: mongodb-1.21.0
                    coverage: none
                    tools: 'composer:v2, flex'

            -
                name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer config extra.symfony.require "${{ matrix.symfony }}"
                    (cd src/Component && composer config extra.symfony.require "${{ matrix.symfony }}")

            -
                name: Restrict ORM version
                if: matrix.orm != ''
                run: |
                    composer require --dev doctrine/orm "${{ matrix.orm }}" --no-update --no-scripts
                    (cd src/Component && composer require --dev doctrine/orm "${{ matrix.orm }}" --no-update --no-scripts)

            -
                name: Remove hateoas on Symfony 7
                if: matrix.symfony == '^7.0'
                run: composer remove --dev willdurand/hateoas-bundle --no-update --no-scripts

            -
                name: Install Behat transliterator
                if: matrix.behat-transliterator != ''
                run: |
                    composer require --dev behat/transliterator "${{ matrix.behat-transliterator }}" --no-update --no-scripts

            -
                name: Install FriendsOfSymfony Rest Bundle
                if: matrix.fos-rest-bundle != ''
                run: |
                    composer require --dev friendsofsymfony/rest-bundle "${{ matrix.fos-rest-bundle }}" --no-update --no-scripts

            -
                name: Install Gedmo Doctrine Extension
                if: matrix.gedmo-doctrine-extensions != ''
                run: |
                    composer require --dev gedmo/doctrine-extensions "${{ matrix.gedmo-doctrine-extensions }}" --no-update --no-scripts

            -
                name: Install MongoDB ODM package
                run: |
                    composer require --dev doctrine/mongodb-odm-bundle "^5.0" --no-update --no-scripts
                    (cd src/Component && composer require --dev doctrine/mongodb-odm "^2.8" --no-update --no-scripts)

            -
                name: Install dependencies
                run: |
                    composer update ${{ matrix.composer-flags }}
                    (cd src/Component && composer update ${{ matrix.composer-flags }})

            -
                name: Prepare test application
                run: |
                    (cd tests/Application && bin/console doctrine:schema:create)

            -
                name: Run PHPStan
                run: vendor/bin/phpstan analyse --ansi --memory-limit=-1 -c phpstan.neon src

            -
                name: Run analysis
                run: |
                    composer analyse
                    (cd src/Component && composer validate --strict)

            -
                name: Run PHPUnit tests
                run: vendor/bin/phpunit --colors=always

            -
                name: Run lint container
                run: (cd tests/Application && bin/console lint:container)

            -
                name: Run state machine PHPUnit tests with winzou/state-machine package
                run: |
                    sed -i -e 's/state_machine_component: symfony/state_machine_component: winzou/g' tests/Application/config/packages/test/sylius_resource.yaml
                    (cd tests/Application && bin/console cache:clear)
                    vendor/bin/phpunit --colors=always
                    sed -i -e 's/state_machine_component: winzou/state_machine_component: symfony/g' tests/Application/config/packages/test/sylius_resource.yaml

            -
                name: Run state machine PHPUnit tests with symfony/workflow package
                run: |
                    sed -i -e 's/state_machine_component: winzou/state_machine_component: symfony/g' tests/Application/config/packages/test/sylius_resource.yaml
                    (cd tests/Application && bin/console cache:clear)
                    vendor/bin/phpunit --colors=always
                    sed -i -e 's/state_machine_component: symfony/state_machine_component: winzou/g' tests/Application/config/packages/test/sylius_resource.yaml

            -
                name: Run lint container without friendsofsymfony/rest-bundle, willdurand/hateoas-bundle & jms/serializer-bundle packages
                run: |
                    composer remove --dev friendsofsymfony/rest-bundle willdurand/hateoas-bundle jms/serializer-bundle --no-scripts
                    (cd tests/Application && bin/console cache:clear --env=test_without_fosrest)
                    (cd tests/Application && bin/console lint:container --env=test_without_fosrest)
                    composer require --dev friendsofsymfony/rest-bundle willdurand/hateoas-bundle jms/serializer-bundle --no-scripts

            -
                name: Run lint container without winzou/state-machine-bundle package
                run: |
                    composer remove --dev winzou/state-machine-bundle --no-scripts
                    (cd tests/Application && bin/console cache:clear --env=test_without_state_machine)
                    (cd tests/Application && bin/console lint:container --env=test_without_state_machine)
                    composer require --dev winzou/state-machine-bundle --no-scripts

            -
                name: Run lint container without sylius/grid-bundle package
                run: |
                    find tests/Application/src -type f -name '*Grid.php' -delete
                    composer remove sylius/grid-bundle --no-scripts --dev
                    (cd tests/Application && bin/console cache:clear --env=test_without_twig)
                    (cd tests/Application && bin/console lint:container --env=test_without_twig)
                    composer require "sylius/grid-bundle: ^1.11" --no-scripts --dev

    tests_with_skeleton:
        runs-on: ubuntu-latest
        name: "Tests with the Symfony Skeleton PHP ${{ matrix.php }}${{ matrix.skeleton != '' && format(', Skeleton {0}', matrix.skeleton) || '' }}"
        strategy:
            fail-fast: false
            matrix:
                php: ["8.3"]
                skeleton: ["^6", "^7"]

        steps:
            -
                uses: actions/checkout@v4
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    extensions: mongodb-1.21.0
                    coverage: none

            -
                name: Create-project with skeleton
                run: |
                    set -x
                    composer create-project --ansi "symfony/skeleton:${{ matrix.skeleton }}" skeleton_app
                    cd skeleton_app
                    composer config extra.symfony.allow-contrib true
                    composer config repositories.local '{"type": "path", "url": "../", "options": {"symlink": true}}' --json
                    composer require -W --ansi sylius/resource-bundle "*@dev"
